use anyhow::{bail, Context, Result};
use clap::Parser;
use std::{fs, path::PathBuf};
use tmv_backend_core::{
    EffectsMode, EffectsRenderer, FolderCounts, FolderFavoriteInput, FolderFavoriteOutput,
    FolderIdentity, FolderMediaFilter, FolderMode, FolderPayload, FolderPreview,
    FolderPreviewBatchError, FolderPreviewBatchInput, FolderPreviewBatchOutput, FolderTotals,
    MediaItem, MediaKind, PerfDiagEvent, PerfDiagEventsInput, PreviewDiagEvent,
    PreviewDiagEventsInput, PreviewDiagPhase, SystemUsageAccount, SystemUsageFile,
    SystemUsageReport, ViewerAccountSortMode, ViewerMediaSortMode, ViewerPreferences, ViewerTheme,
};
use ts_rs::TS;

const HEADER: &str =
    "// Generated by `cargo run -p tmv-contract-export`\n// Do not edit manually.\n\n";

#[derive(Parser)]
struct Cli {
    #[arg(long)]
    check: bool,

    #[arg(long)]
    output: Option<PathBuf>,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let output_path = cli.output.unwrap_or_else(default_output_path);
    let rendered = render_contracts();

    if cli.check {
        let existing = fs::read_to_string(&output_path)
            .with_context(|| format!("read existing contract file {}", output_path.display()))?;
        if existing != rendered {
            bail!(
                "Generated contracts are out of date: {}",
                output_path.display()
            );
        }
        return Ok(());
    }

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create output directory {}", parent.display()))?;
    }
    fs::write(&output_path, rendered)
        .with_context(|| format!("write generated contract file {}", output_path.display()))?;
    Ok(())
}

fn default_output_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..")
        .join("web")
        .join("src")
        .join("generated")
        .join("tmv-contract.ts")
}

fn render_contracts() -> String {
    let sections = [
        export_decl::<MediaKind>(),
        export_decl::<MediaItem>(),
        export_decl::<FolderCounts>(),
        export_decl::<FolderPreview>(),
        export_decl::<FolderIdentity>(),
        export_decl::<FolderTotals>(),
        export_decl::<FolderPayload>(),
        export_decl::<FolderMode>(),
        export_decl::<FolderMediaFilter>(),
        export_decl::<FolderPreviewBatchInput>(),
        export_decl::<FolderPreviewBatchError>(),
        export_decl::<FolderPreviewBatchOutput>(),
        export_decl::<FolderFavoriteInput>(),
        export_decl::<FolderFavoriteOutput>(),
        export_decl::<SystemUsageFile>(),
        export_decl::<SystemUsageAccount>(),
        export_decl::<SystemUsageReport>(),
        export_decl::<ViewerAccountSortMode>(),
        export_decl::<ViewerMediaSortMode>(),
        export_decl::<ViewerTheme>(),
        export_decl::<ViewerPreferences>(),
        export_decl::<PreviewDiagPhase>(),
        export_decl::<PreviewDiagEvent>(),
        export_decl::<PreviewDiagEventsInput>(),
        export_decl::<EffectsMode>(),
        export_decl::<EffectsRenderer>(),
        export_decl::<PerfDiagEvent>(),
        export_decl::<PerfDiagEventsInput>(),
    ];

    let mut output = String::from(HEADER);
    output.push_str(&sections.join("\n\n"));
    output.push('\n');
    output
}

fn export_decl<T: TS>() -> String {
    let decl = T::decl();
    if decl.starts_with("export ") {
        decl
    } else {
        format!("export {decl}")
    }
}
